from enum import StrEnum


class ReasonCode(StrEnum):
    ORDER_NOT_DELIVERED = "ORDER_NOT_DELIVERED"
    OUTSIDE_RETURN_WINDOW = "OUTSIDE_RETURN_WINDOW"
    FINAL_SALE = "FINAL_SALE"
    USED_ITEM = "USED_ITEM"
    DEFECT_REQUIRES_REVIEW = "DEFECT_REQUIRES_REVIEW"
    ORDER_ALREADY_RETURNED = "ORDER_ALREADY_RETURNED"
    IDENTITY_MISMATCH = "IDENTITY_MISMATCH"
    MISSING_ORDER_ID = "MISSING_ORDER_ID"
    MISSING_ITEM_SELECTION = "MISSING_ITEM_SELECTION"
    MISSING_RETURN_REASON = "MISSING_RETURN_REASON"
    MISSING_USAGE_STATUS = "MISSING_USAGE_STATUS"
    INFORMATION_CONFLICT = "INFORMATION_CONFLICT"
    USER_REQUESTED_HUMAN = "USER_REQUESTED_HUMAN"
    POLICY_NOT_COVERED = "POLICY_NOT_COVERED"
    SYSTEM_ERROR = "SYSTEM_ERROR"
    ELIGIBLE = "ELIGIBLE"
